### ISSUE TITLE
有教程或者博客地址吗？

### ISSUE THREAD

**Issue by izhaojinlong** [AdamZhuang/machine-learning#1]
这个项目怎么运行或者测试啊，想改成自己的图片测试一下不知道怎么弄，求指导

**Comment by AdamZhuang** [comment]
额，现在才看到，你现在应该不需要了吧。

这个之前代码写的十分粗糙，如果有需要的话，直接看这俩，有模型解释。
[基于SRCNN的表情包超分辨率（附tensorflow实现）](https://blog.csdn.net/m0_37510087/article/details/79367649)
[基于vgg19模型的 style transfer](https://blog.csdn.net/m0_37510087/article/details/79281098)
